In [1]:
import pandas as pd

In [12]:
info={

   "Name":["harsh","Trisah","sanket"],
    "age":[21,21,20]
}

df=pd.DataFrame(info)
print(df)

     Name  age
0   harsh   21
1  Trisah   21
2  sanket   20

In [13]:
df

     Name  age
0   harsh   21
1  Trisah   21
2  sanket   20

In [11]:
#Series

df=[2,3,1,4,2]
print(df)

[2, 3, 1, 4, 2]

In [15]:
a=pd.Series(df,index=["a","b",3,"d","s"])
print(a.index)

Index(['a', 'b', 3, 'd', 's'], dtype='object')

In [20]:

a=pd.Series([1,2,3,4,5]);
b=pd.Series([10,20,30,40,50])


df=(a+b)
print(df)

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [23]:
info={
    "name":["harsh","trisha","Utkarsh"],
    "age":[21,21,20]
}

# df=pd.DataFrame(info)
# print(df)

      name  age
0    harsh   21
1   trisha   21
2  Utkarsh   20

In [24]:
df

      name  age
0    harsh   21
1   trisha   21
2  Utkarsh   20

In [30]:

df=pd.DataFrame(info,index=[11,22,33],columns=["a","b","c"])
print(df.index)
print(df.columns)

Index([11, 22, 33], dtype='int64')
Index(['a', 'b', 'c'], dtype='object')

In [35]:
#csv 
df=pd.read_csv("raw_data.csv")
print(df,type(df))

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0 <class 'pandas.core.frame.DataFrame'>

In [37]:
# df=pd.read_json("employee_data.json")
# print(df,type(df))

In [51]:
df.head()
df.tail()
df.sample()
df.info();
df.describe()
df.shape
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64